[darwin]
  [darwin.brews]
    taps = [
      "siderolabs/tap",
      "fluxcd/tap",
    ]

    formulae = [
      "chezmoi",
      "direnv",
      "eza",
      "gh",
      "git",
      "go-task",
      "helm",
      "kubectl",
      "mas",          # add mas CLI to install App Store apps
      "mise",
      "neovim",
      "pam-reattach",  # Touch ID for sudo in tmux/screen
      "rustup",
      "siderolabs/tap/sidero-tools",
      "sops",
      "starship",
      "zoxide",
      "fluxcd/tap/flux",
    ]

    casks = [
      "1password-cli",
      "brave-browser",
      "font-meslo-lg-nerd-font",
      "ghostty",
      "private-internet-access",
      "visual-studio-code",
      "warp",
      "docker-desktop",
    ]

  [darwin.mas]
    apps = [
      "417375580:BetterSnapTool",
    ]

[windows]
  [windows.winget]
    packages = [
      "AgileBits.1Password",
      "AgileBits.1Password.CLI",
      "Git.Git",
      "Microsoft.WindowsTerminal",
      "Microsoft.PowerShell",
      "Neovim.Neovim",
      "sharkdp.hyperfine",
      "Starship.Starship",
      "direnv.direnv",
      "Microsoft.VisualStudioCode",
    ]